version: '3'

tasks:
  lint:
    desc: Lint markdown files
    cmds:
      - npx markdownlint $(find . -name "*.md" -not -path "./node_modules/*")

  lint:fix:
    desc: Lint and fix markdown files
    cmds:
      - npx markdownlint --fix $(find . -name "*.md" -not -path "./node_modules/*")

  install:
    desc: Install dependencies
    cmds:
      - npm install
